In [1]:
import torch

In [4]:
material_cost = torch.tensor(10,requires_grad=True,dtype=torch.float16)
labor_cost = torch.tensor(87,requires_grad=True,dtype=torch.float16)

total_cost = 3*material_cost**2 + 5*labor_cost + 100
total_cost

tensor(835., dtype=torch.float16, grad_fn=<AddBackward0>)

In [5]:
total_cost.backward()
material_cost.grad,labor_cost.grad

(tensor(60., dtype=torch.float16), tensor(5., dtype=torch.float16))

In [26]:
a = torch.tensor([10], requires_grad=True, dtype=torch.float16)
b = a**2
b.backward()
a.grad

tensor([20.], dtype=torch.float16)

In [27]:
a = torch.tensor([10,20], requires_grad=True, dtype=torch.float16)
b = a**2
b.backward()
a.grad

RuntimeError: grad can be implicitly created only for scalar outputs

In [28]:
a = torch.tensor([10,20], requires_grad=True, dtype=torch.float16)
b = a**2
result = b.sum()
result.backward()
a.grad

tensor([20., 40.], dtype=torch.float16)

In [29]:
a = torch.tensor([[10,20],[1,2]], requires_grad=True, dtype=torch.float16)
b = a**2
result = b.sum()
result.backward()
a.grad

tensor([[20., 40.],
        [ 2.,  4.]], dtype=torch.float16)