In [1]:
import torch

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"using device {device}")

using device cuda


**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [3]:
#1 Create a PyTorch Tensor from the following inventory data
inventory = [[12, 15, 10, 0, 5],
             [10, 8, 7, 5, 4],
             [20, 10, 15, 5, 2]]

inventory_tensor = torch.tensor(inventory)
print(inventory_tensor)

tensor([[12, 15, 10,  0,  5],
        [10,  8,  7,  5,  4],
        [20, 10, 15,  5,  2]])


In [4]:
#2 Find the total inventory for each item across all days

total_inventory = inventory_tensor.sum(dim=0)
print(total_inventory)

tensor([42, 33, 32, 10, 11])


In [5]:
#3 Find the average inventory per day

average_inventory = inventory_tensor.mean(dim=1,dtype=torch.float32)
print(average_inventory)

tensor([ 8.4000,  6.8000, 10.4000])


**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [6]:
#1 Simulate this data using PyTorch's Random Functions

road1 = torch.randint(50, 200, (24,))
road2 = torch.randint(50, 200, (24,))
print(road1)
print(road2)

tensor([106,  82,  97, 118,  64, 179, 127,  93,  99, 140, 133, 129, 106, 129,
         56, 191,  67, 187, 129,  99, 182, 131, 136, 142])
tensor([139,  89, 159, 158, 119, 153, 149, 130,  73, 110, 185, 133, 108, 183,
        172,  60,  99, 190, 114, 111, 142, 117, 100,  83])


In [7]:
#2 Write the function to calculate the total vehicle flow for each road across the entire day
total_flow_road1 = road1.sum() 
total_flow_road2 = road2.sum() 
print(total_flow_road1)
print(total_flow_road2)

tensor(2922)
tensor(3076)


In [8]:
#3 Write the function to calculate the total vehicle flow for each hour across both roads
total_flow_hourly  = road1 + road2
print(total_flow_hourly)

tensor([245, 171, 256, 276, 183, 332, 276, 223, 172, 250, 318, 262, 214, 312,
        228, 251, 166, 377, 243, 210, 324, 248, 236, 225])


**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [9]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]

fitness = torch.tensor([[10, 20, 30],
                        [40, 50, 60],
                        [70, 80, 90]])
weights = torch.tensor([0.8, 1.2, 1.5])
weighted_fitness = weights * fitness
print(weighted_fitness)

tensor([[  8.0000,  24.0000,  45.0000],
        [ 32.0000,  60.0000,  90.0000],
        [ 56.0000,  96.0000, 135.0000]])


In [10]:
#2 Find the row-wise and column-wise maximum scores

row_max = weighted_fitness.max(dim=1) 
col_max = weighted_fitness.max(dim=0) 
print(row_max)
print(col_max)

torch.return_types.max(
values=tensor([ 45.,  90., 135.]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([ 56.,  96., 135.]),
indices=tensor([2, 2, 2]))


In [11]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)

transposed_fitness = fitness.t()
print(transposed_fitness)


tensor([[10, 40, 70],
        [20, 50, 80],
        [30, 60, 90]])


**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [12]:
#1 Use PyTorch to compute 'y' for x = 4

x = torch.tensor(4,requires_grad=True,dtype=torch.float32)
y = 2*x**3+5*x**2-3*x+7
print(y)

tensor(203., grad_fn=<AddBackward0>)


In [13]:
#2 Calculate dy/dx (gradient) using PyTorch's autograd

y.backward(retain_graph=True)
gradient = x.grad
print(gradient)

tensor(133.)


In [14]:
y.backward()

**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [15]:
camera1 = torch.tensor([[1, 2], [3, 4]])
camera2 = torch.tensor([[5, 6], [7, 8]])

In [16]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)
elementwise_product = camera1 * camera2
print(elementwise_product)

tensor([[ 5, 12],
        [21, 32]])


In [17]:
#2 Compute Dot Product of the two matrices
dot_product = torch.matmul(camera1, camera2)
print(dot_product)

tensor([[19, 22],
        [43, 50]])


In [18]:
#3 Compute the Determinant of each matrix
det_camera1 = torch.det(camera1.float())
det_camera2 = torch.det(camera2.float())
print(det_camera1)
print(det_camera2)

tensor(-2.)
tensor(-2.0000)


**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [20]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]

w = torch.tensor(2.0,requires_grad =True)
b = torch.tensor(1.0,requires_grad =True)

x = torch.tensor([1,2,3,4])
print(w)
print(b)
print(x)

tensor(2., requires_grad=True)
tensor(1., requires_grad=True)
tensor([1, 2, 3, 4])


In [21]:
#2 Compute tensors for y
y = w * x + b
print(y)

tensor([3., 5., 7., 9.], grad_fn=<AddBackward0>)


In [23]:
y.sum().backward(retain_graph=True)

In [24]:
w.grad

tensor(10.)

In [25]:
b.grad

tensor(4.)