In [1]:
import torch

In [2]:
units = torch.tensor([
    [200,220],  #product A (iphone)
    [150,180],  #product B (ipad)
    [300,330]   #product C (macBook)
])

In [3]:
units.shape

torch.Size([3, 2])

In [4]:
units.dtype

torch.int64

In [5]:
units.device

device(type='cpu')

In [6]:
units.view(-1)

tensor([200, 220, 150, 180, 300, 330])

In [7]:
units.view(2,3)

tensor([[200, 220, 150],
        [180, 300, 330]])

In [8]:
units.view(6,1)

tensor([[200],
        [220],
        [150],
        [180],
        [300],
        [330]])