In [2]:
import torch

 single value as tensor

In [7]:
torch.tensor(9)

tensor(9)

array values as tensor

In [10]:
a = torch.tensor([1,2,3,4])

In [11]:
a

tensor([1, 2, 3, 4])

tesnor slicing

In [12]:
a[:2]

tensor([1, 2])

In [14]:
a[2]

tensor(3)

matrices as tensor

In [17]:
# Sales datafor Quater 1 (matrix 1)
# Rows represent different products, columns represents diffrent regions

q1 = torch.tensor([
    [200,220,250],   # product A (iphone)
    [150,180,210],   # product B (ipad)
    [300,330,360]    # product C (MacBook)
])

q2= torch.tensor([
    [209,231,259], # product A (iphone)
    [155,192,222], # product B (ipad)
    [310,340,375]   # product C (MacBook)
])

In [18]:
q1 +q2

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 735]])

In [19]:
q2-q1

tensor([[ 9, 11,  9],
        [ 5, 12, 12],
        [10, 10, 15]])

In [21]:
(q2-q1)*100/q1

tensor([[4.5000, 5.0000, 3.6000],
        [3.3333, 6.6667, 5.7143],
        [3.3333, 3.0303, 4.1667]])

In [22]:
return_rate = 0.1

In [23]:
return_rate*q1

tensor([[20., 22., 25.],
        [15., 18., 21.],
        [30., 33., 36.]])

In [24]:
# profit per unit is given product and region wise
# calculate total profit for all units per region, per product

profit_per_unit = torch.tensor([
    [30,27,25],
    [10,18,17],
    [45,38,39]
])

In [25]:
profit_per_unit * q1

tensor([[ 6000,  5940,  6250],
        [ 1500,  3240,  3570],
        [13500, 12540, 14040]])

In [27]:
product_prices = torch.tensor([[1100,450,1500]])
product_prices

tensor([[1100,  450, 1500]])

In [28]:
# revenue per product
torch.matmul(product_prices,q1)

tensor([[737500, 818000, 909500]])

In [29]:
product_prices

tensor([[1100,  450, 1500]])

In [30]:
product_prices.t()

tensor([[1100],
        [ 450],
        [1500]])

In [32]:
q1

tensor([[200, 220, 250],
        [150, 180, 210],
        [300, 330, 360]])

In [33]:
# revenue per region

prices_by_region=q1*product_prices.t()
prices_by_region

tensor([[220000, 242000, 275000],
        [ 67500,  81000,  94500],
        [450000, 495000, 540000]])

In [34]:
prices_by_region.sum()

tensor(2465000)

In [36]:
prices_by_region.sum(dim=0)

tensor([737500, 818000, 909500])

protfoila example

In [37]:
# Create portfolio composition matrix (3x3)
# Rows: Different portfolios (P1, P2, P3)
# Columns: Asset allocation (Stocks, Bonds, Real Estate)
portfolio_composition = torch.tensor([
    [100.0, 50.0, 30.0],  # P1
    [80.0, 70.0, 20.0],   # P2
    [60.0, 40.0, 90.0]    # P3
], dtype=torch.float32)

# Create price change matrix (3x3)
# Rows: Assets (Stocks, Bonds, Real Estate)
# Columns: Economic scenarios (Growth, Neutral, Recession)
price_changes = torch.tensor([
    [1.15, 1.05, 0.85],  # Stocks
    [1.05, 1.02, 1.10],  # Bonds
    [1.10, 1.00, 0.90]   # Real Estate
], dtype=torch.float32)

values = torch.matmul(portfolio_composition, price_changes)
values

tensor([[200.5000, 186.0000, 167.0000],
        [187.5000, 175.4000, 163.0000],
        [210.0000, 193.8000, 176.0000]])

In [38]:
# Assume that this portfolio is in USD. You want to convert that to INR 
# Assume USD to INR conversion rate to be 83

values_inr = 83*values
values_inr

tensor([[16641.5000, 15438.0000, 13861.0000],
        [15562.5000, 14558.1992, 13529.0000],
        [17430.0000, 16085.3994, 14608.0000]])

GPU Accelaration

In [39]:
torch.cuda.is_available()

True

In [40]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Using GPU for large-scale customer data processing")
else:
    device = torch.device("cpu")
    print("Using CPU for customer data processing")

Using GPU for large-scale customer data processing


In [41]:
device

device(type='cuda')

In [42]:
# Simulating customer data with 1 million customers and 3 features (age, spending score, income)

customer_data = torch.rand(1_000_000, 3, device=device)
customer_data.shape

torch.Size([1000000, 3])

In [44]:
customer_data[:8]

tensor([[0.5274, 0.3681, 0.8630],
        [0.8401, 0.8111, 0.1725],
        [0.2950, 0.0637, 0.7021],
        [0.7310, 0.1970, 0.3734],
        [0.3356, 0.5957, 0.5695],
        [0.7988, 0.0844, 0.3689],
        [0.2606, 0.7396, 0.0365],
        [0.4055, 0.7628, 0.6202]], device='cuda:0')

In [48]:
customer_data[:,1]

tensor([0.3681, 0.8111, 0.0637,  ..., 0.2503, 0.0642, 0.7046], device='cuda:0')

In [49]:
high_spending_cus = customer_data[customer_data[:,1] >0.5]
high_spending_cus

tensor([[0.8401, 0.8111, 0.1725],
        [0.3356, 0.5957, 0.5695],
        [0.2606, 0.7396, 0.0365],
        ...,
        [0.9787, 0.8335, 0.5583],
        [0.0600, 0.9034, 0.9918],
        [0.8097, 0.7046, 0.8262]], device='cuda:0')

In [50]:
high_spending_cus.shape

torch.Size([499914, 3])

In [51]:
high_spending_cus.to("cpu")

tensor([[0.8401, 0.8111, 0.1725],
        [0.3356, 0.5957, 0.5695],
        [0.2606, 0.7396, 0.0365],
        ...,
        [0.9787, 0.8335, 0.5583],
        [0.0600, 0.9034, 0.9918],
        [0.8097, 0.7046, 0.8262]])