In [12]:
import pandas as pd

df = pd.read_csv("bonus.csv")
df.head()

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    1                   3    116
1     EMP_002            4                    8                  10    136
2     EMP_003            8                    4                   5    150
3     EMP_004            5                    4                   7    118
4     EMP_005            7                    5                   6    146

In [13]:
df.shape

(1000, 5)

In [14]:
from sklearn.model_selection import train_test_split

X = df[['performance','years_of_experience','projects_completed']].values
y =df[['bonus']].values

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [15]:
X_train.shape

(800, 3)

In [16]:
X_test.shape

(200, 3)

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim

In [18]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [21]:
class BonusPredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(3,1)  #3 input and 1 ouput (bias internally created automatically)
        )
    def forward(self,x):
        return self.network(x)

In [24]:
model = BonusPredictor()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.005)

In [25]:
epochs = 5000
for epoch in range(epochs):
    # 1. Forward pass
    predictions = model(X_train_tensor)
    loss = criterion(predictions,y_train_tensor)
    
    # 2. backward pass
    optimizer.zero_grad()
    loss.backward()
    
    # 3. update the weights
    optimizer.step()
    
    
    if (epoch +1)%100 ==0:
        print(f"Epoch [{epoch +1}/{epochs}], loss: {loss.item(): 0.2f}")

Epoch [100/5000], loss:  21.71
Epoch [200/5000], loss:  18.85
Epoch [300/5000], loss:  16.51
Epoch [400/5000], loss:  14.50
Epoch [500/5000], loss:  12.76
Epoch [600/5000], loss:  11.23
Epoch [700/5000], loss:  9.89
Epoch [800/5000], loss:  8.70
Epoch [900/5000], loss:  7.66
Epoch [1000/5000], loss:  6.75
Epoch [1100/5000], loss:  5.94
Epoch [1200/5000], loss:  5.23
Epoch [1300/5000], loss:  4.61
Epoch [1400/5000], loss:  4.05
Epoch [1500/5000], loss:  3.57
Epoch [1600/5000], loss:  3.14
Epoch [1700/5000], loss:  2.77
Epoch [1800/5000], loss:  2.44
Epoch [1900/5000], loss:  2.15
Epoch [2000/5000], loss:  1.89
Epoch [2100/5000], loss:  1.66
Epoch [2200/5000], loss:  1.46
Epoch [2300/5000], loss:  1.29
Epoch [2400/5000], loss:  1.14
Epoch [2500/5000], loss:  1.00
Epoch [2600/5000], loss:  0.88
Epoch [2700/5000], loss:  0.77
Epoch [2800/5000], loss:  0.68
Epoch [2900/5000], loss:  0.60
Epoch [3000/5000], loss:  0.53
Epoch [3100/5000], loss:  0.47
Epoch [3200/5000], loss:  0.41
Epoch [3300

In [27]:
model.eval()

with torch.no_grad():
    test_predictions= model(X_test_tensor)
    test_loss = criterion(test_predictions, y_test_tensor)

    print(f"Test  Loss: {test_loss.item(): 0.2f}")

Test  Loss:  0.04


In [28]:
test_predictions[:4]

tensor([[189.9580],
        [150.1558],
        [113.7308],
        [ 51.7011]])

In [29]:
y_test_tensor[:4]

tensor([[190.],
        [150.],
        [114.],
        [ 52.]])

In [30]:
for name, value in model.named_parameters():
    print(f"Name: {name}, Value: {value}")

Name: network.0.weight, Value: Parameter containing:
tensor([[12.0334,  5.8425,  2.1876]], requires_grad=True)
Name: network.0.bias, Value: Parameter containing:
tensor([19.2323], requires_grad=True)
