In [1]:
import torch
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv("bonus_dataset.csv")
df.head()

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    2                   4    124
1     EMP_002            4                    1                   4     82
2     EMP_003            8                    7                  10    178
3     EMP_004            5                    7                   8    138
4     EMP_005            7                    8                   9    170

In [3]:
df.shape

(100, 5)

In [4]:
df['performance'].values

array([ 7,  4,  8,  5,  7, 10,  3,  7,  8,  5,  4,  8,  8,  3,  6,  5,  2,
        8,  6,  2,  5,  1, 10,  6,  9,  1, 10,  3,  7,  4,  9,  3,  5,  3,
        7,  5,  9,  7,  2,  4,  9,  2, 10,  9, 10,  5,  2,  4,  7,  8,  3,
        1,  4,  2,  8,  4,  2,  6,  6, 10,  4,  6,  2, 10,  2, 10,  4,  8,
        7,  9,  8,  5,  2,  5,  8, 10,  9,  9,  1,  9,  7,  9,  8,  1,  8,
        8,  3,  1,  8,  3,  3,  1,  5, 10,  7, 10,  9,  7,  9,  8],
      dtype=int64)

In [5]:
type(df['performance'].values)

numpy.ndarray

In [6]:
performance = torch.tensor(df['performance'].values, dtype=torch.float32)
years_of_experience = torch.tensor(df['years_of_experience'].values, dtype=torch.float32)
projects_completed = torch.tensor(df['projects_completed'].values, dtype=torch.float32)
bonus = torch.tensor(df['bonus'].values, dtype=torch.float32)

In [22]:
w1 = torch.rand(1,requires_grad=True)
w2 = torch.rand(1,requires_grad=True)
w3 = torch.rand(1,requires_grad=True)
bias = torch.rand(1,requires_grad=True)

w1,w2,w3,bias

(tensor([0.1166], requires_grad=True),
 tensor([0.0549], requires_grad=True),
 tensor([0.7320], requires_grad=True),
 tensor([0.3553], requires_grad=True))

In [23]:
epochs = 5000
learning_rate =0.006

for epoch in range(epochs):
    
    predicted_bonus = w1*performance + w2*years_of_experience + w3*projects_completed + bias
    loss = ((predicted_bonus - bonus)**2).mean()
    
    loss.backward()
    with torch.no_grad():
        w1-=learning_rate*w1.grad
        w2-=learning_rate*w2.grad
        w3-=learning_rate*w3.grad
        bias-=learning_rate*bias.grad
    w1.grad.zero_()
    w2.grad.zero_()
    w3.grad.zero_()
    bias.grad.zero_()
    
    if epoch % 100==0:
        print(f"Epoch: {epoch}, loss: {loss.item():0.2f}")
    
    
    

Epoch: 0, loss: 18256.93
Epoch: 100, loss: 18.15
Epoch: 200, loss: 15.82
Epoch: 300, loss: 13.80
Epoch: 400, loss: 12.04
Epoch: 500, loss: 10.51
Epoch: 600, loss: 9.17
Epoch: 700, loss: 8.00
Epoch: 800, loss: 6.98
Epoch: 900, loss: 6.10
Epoch: 1000, loss: 5.32
Epoch: 1100, loss: 4.64
Epoch: 1200, loss: 4.05
Epoch: 1300, loss: 3.54
Epoch: 1400, loss: 3.09
Epoch: 1500, loss: 2.69
Epoch: 1600, loss: 2.35
Epoch: 1700, loss: 2.05
Epoch: 1800, loss: 1.79
Epoch: 1900, loss: 1.56
Epoch: 2000, loss: 1.36
Epoch: 2100, loss: 1.19
Epoch: 2200, loss: 1.04
Epoch: 2300, loss: 0.91
Epoch: 2400, loss: 0.79
Epoch: 2500, loss: 0.69
Epoch: 2600, loss: 0.60
Epoch: 2700, loss: 0.53
Epoch: 2800, loss: 0.46
Epoch: 2900, loss: 0.40
Epoch: 3000, loss: 0.35
Epoch: 3100, loss: 0.31
Epoch: 3200, loss: 0.27
Epoch: 3300, loss: 0.23
Epoch: 3400, loss: 0.20
Epoch: 3500, loss: 0.18
Epoch: 3600, loss: 0.15
Epoch: 3700, loss: 0.13
Epoch: 3800, loss: 0.12
Epoch: 3900, loss: 0.10
Epoch: 4000, loss: 0.09
Epoch: 4100, loss: 

In [24]:
w1.item(),w2.item(),w3.item(),bias.item()

(12.027575492858887, 5.905402660369873, 2.1261985301971436, 19.383800506591797)